/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\public\models\phonix\scene.gltf 
Author: Daniel Zhabotinsky (https://sketchfab.com/DanielZhabotinsky)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/phoenix-455-71-low-poly-model-955edc733c6d44fabc0ad7c246a15896
Title: Phoenix 455 '71 - Low poly model
*/

import React, { useRef, memo, useEffect } from "react";
import { useGLTF } from "@react-three/drei";
import Car from "../../components/car";
import Vehicle from "../../entities/Vehicle";
import { entityManager } from "../../entities/EntityManager";
import useVehicleAnimation from "../../hooks/useVehicleAnimation";
import useFollowCamera from "../../hooks/useFollowCamera";

export const Model = memo(function Model(props) {
  const { nodes, materials } = useGLTF('/models/phonix/scene.gltf')

  const carRef = useRef();
  const vehicleRef = useRef(null);

  useEffect(() => {
    const v = new Vehicle("Phoenix");
    if (props.position) {
      v.position.x = props.position[0];
      v.position.y = props.position[1];
      v.position.z = props.position[2];
    }
    entityManager.add(v);
    vehicleRef.current = v;

    return () => {
      entityManager.remove(v);
    };
  }, [props.position]);

  const frontLeftSteerRef = useRef();
  const frontRightSteerRef = useRef();

  const frontLeftWheelRef = useRef();
  const frontRightWheelRef = useRef();
  const rearLeftWheelRef = useRef();
  const rearRightWheelRef = useRef();

  useVehicleAnimation({
    vehicleRef,
    carRef,
    frontLeftSteerRef,
    frontRightSteerRef,
    frontLeftWheelRef,
    frontRightWheelRef,
    rearLeftWheelRef,
    rearRightWheelRef,
  });

  useFollowCamera({ vehicleRef });

  return (
    <group ref={carRef} {...props} dispose={null}>
      <group rotation={[-1.569, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-0.029, 0.765, 0]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={2.648}>
            <mesh geometry={nodes.Phoenix445_Body_Phoenix445_Bodymat_0.geometry} material={materials.Phoenix445_Bodymat} position={[0.067, 0.167, 0.227]} />
          </group>
          <group position={[-2.348, 0.571, 0]} rotation={[-Math.PI / 2, -0.196, Math.PI / 2]} scale={2.648}>
            <mesh geometry={nodes.Phoenix445_Bumper_rear_UCB_BOTTOM_0.geometry} material={materials.UCB_BOTTOM} position={[0.252, -0.009, 0.035]} />
          </group>
          <group position={[1.4, 0.868, 0]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={2.648}>
            <mesh geometry={nodes.Phoenix445_Hood_Phoenix445_Bodymat_0.geometry} material={materials.Phoenix445_Bodymat} position={[0.067, 0.707, 0.188]} />
          </group>
          <group position={[-2.013, 0.895, 0]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={2.648}>
            <mesh geometry={nodes.Phoenix445_Trunkdoor_Phoenix445_Bodymat_0.geometry} material={materials.Phoenix445_Bodymat} position={[0.067, -0.582, 0.178]} />
          </group>
          <group position={[-0.197, 1.06, 0.773]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={2.648}>
            <mesh geometry={nodes.Phoenix445_Glass_Passenger_UCB_Lights_and_Glass_Transperent_0.geometry} material={materials.UCB_Lights_and_Glass_Transperent} position={[0.357, 0.103, 0.116]} />
          </group>
          <group position={[0.399, 1.096, 0]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={2.648}>
            <mesh geometry={nodes.Phoenix445_Windshield_UCB_Lights_and_Glass_Transperent_0.geometry} material={materials.UCB_Lights_and_Glass_Transperent} position={[0.067, 0.329, 0.102]} />
          </group>
          <group position={[-0.074, 0.306, 0]} rotation={[-Math.PI / 2, 0, -Math.PI]}>
            <mesh geometry={nodes.Phoenix445_Suspension_UCB_BOTTOM_0.geometry} material={materials.UCB_BOTTOM} position={[-1.57, 0.345, 0.078]} />
          </group>
          <group position={[-0.044, 0.724, 0]} rotation={[-Math.PI / 2, 0, -Math.PI]}>
            <mesh geometry={nodes.Phoenix445_Bottom_UCB_BOTTOM_0.geometry} material={materials.UCB_BOTTOM} position={[0.337, 0.008, -0.36]} />
          </group>
          <group position={[2.285, 0.607, 0]} rotation={[Math.PI, Math.PI / 2, 0]} scale={0.276}>
            <mesh geometry={nodes.Phoenix445_Headlights_glass_UCB_Lights_and_Glass_Transperent_0.geometry} material={materials.UCB_Lights_and_Glass_Transperent} position={[-0.446, 0.399, 0.233]} />
          </group>
          <group position={[-0.466, 0.788, 0]} rotation={[-Math.PI / 2, 0, -Math.PI]}>
            <mesh geometry={nodes.Phoenix445_Interior_UCB_Interiors_2_0.geometry} material={materials.UCB_Interiors_2} position={[-0.084, 0.008, -0.425]} />
          </group>
          <group position={[-2.169, 0.632, 0]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={2.648}>
            <mesh geometry={nodes.Phoenix445_Taillights_Glass_UCB_Lights_and_Glass_Transperent_0.geometry} material={materials.UCB_Lights_and_Glass_Transperent} position={[0.067, -0.711, 0.278]} />
          </group>
          <group position={[-1.299, 1.107, 0]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={2.648}>
            <mesh geometry={nodes.Phoenix445_Glass_rear_UCB_Lights_and_Glass_Transperent_0.geometry} material={materials.UCB_Lights_and_Glass_Transperent} position={[0.067, -0.313, 0.098]} />
          </group>
          <group position={[-0.197, 1.06, -0.773]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={2.648}>
            <mesh geometry={nodes.Phoenix445_Glass_Driver_UCB_Lights_and_Glass_Transperent_0.geometry} material={materials.UCB_Lights_and_Glass_Transperent} position={[-0.227, 0.103, 0.116]} />
          </group>
          <group position={[0.057, 0.79, -0.371]} rotation={[-Math.PI / 2, 0, -Math.PI]}>
            <mesh geometry={nodes.Phoenix445_Steering_Wheel_UCB_Interiors_2_0.geometry} material={materials.UCB_Interiors_2} position={[0.439, 0.379, -0.426]} />
          </group>
          <group position={[2.112, 0.464, 0]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={2.648}>
            <mesh geometry={nodes.Phoenix445_Headlights_Glass001_UCB_Lights_and_Glass_Transperent_0.geometry} material={materials.UCB_Lights_and_Glass_Transperent} position={[0.067, 0.906, 0.341]} />
          </group>
          <group position={[-2.304, 0.706, 0]} rotation={[-Math.PI / 2, 0, -Math.PI]}>
            <mesh geometry={nodes.Phoenix445_Reverse_UCB_Lights_and_Glass_0.geometry} material={materials.UCB_Lights_and_Glass} position={[-1.923, 0.008, -0.343]} />
          </group>
          <group position={[-2.297, 0.707, 0]} rotation={[-Math.PI / 2, 0, -Math.PI]}>
            <mesh geometry={nodes.Phoenix445_Brakelights_UCB_Lights_and_Glass_0.geometry} material={materials.UCB_Lights_and_Glass} position={[-1.915, 0.008, -0.343]} />
          </group>
          <group position={[-0.052, 0.557, 0]} rotation={[-Math.PI / 2, 0, -Math.PI]}>
            <mesh geometry={nodes.Phoenix445_Blinkers_UCB_Lights_and_Glass_0.geometry} material={materials.UCB_Lights_and_Glass} position={[0.33, 0.008, -0.193]} />
          </group>
          <group position={[2.265, 0.607, 0]} rotation={[-Math.PI / 2, 0, -Math.PI]}>
            <mesh geometry={nodes.Phoenix445_Headlights_UCB_Lights_and_Glass_0.geometry} material={materials.UCB_Lights_and_Glass} position={[2.647, 0.008, -0.243]} />
          </group>
          <group position={[1.852, 0.86, 0]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={2.648}>
            <mesh geometry={nodes.Phoenix445_Hood_Inner_UCB_BOTTOM_0.geometry} material={materials.UCB_BOTTOM} position={[0.067, 0.877, 0.191]} />
          </group>
          <Car
            nodes={nodes}
            materials={materials}

            frontLeftSteerRef={frontLeftSteerRef}
            frontRightSteerRef={frontRightSteerRef}

            frontLeftWheelRef={frontLeftWheelRef}
            frontRightWheelRef={frontRightWheelRef}
            rearLeftWheelRef={rearLeftWheelRef}
            rearRightWheelRef={rearRightWheelRef}
          />
          <group position={[-2.419, 0.514, 0]} rotation={[Math.PI / 2, -1.309, Math.PI / 2]}>
            <mesh geometry={nodes.Phoenix455_np_Numberplates_Misk_U_0.geometry} material={materials.Numberplates_Misk_U} position={[0.492, -0.485, -0.002]} />
          </group>
          <group position={[-0.027, 0.653, 0]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[0.928, 0.681, 0.928]}>
            <mesh geometry={nodes.Phoenix445_Body_Badges_Carbadges_misc_U_0.geometry} material={materials.Carbadges_misc_U} position={[-0.205, -1.688, 0.19]} />
          </group>
          <group position={[1.498, 0.326, -0.856]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[1.01, 0.956, 1.01]}>
            <mesh geometry={nodes.Phoenix445_CaliperStock_FL_RB1c_Tire_1k_0.geometry} material={materials.RB1c_Tire_1k} position={[0, -0.002, 0]} />
          </group>
          <group position={[1.498, 0.326, 0.856]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[1.01, 0.956, 1.01]}>
            <mesh geometry={nodes.Phoenix445_CaliperStock_FR_RB1c_Tire_1k_0.geometry} material={materials.RB1c_Tire_1k} position={[0, -0.002, 0]} />
          </group>
          <group position={[-1.242, 0.326, -0.856]} rotation={[Math.PI / 2, 0, 0]} scale={[1.01, 0.956, 1.01]}>
            <mesh geometry={nodes.Phoenix445_CaliperStock_RL_RB1c_Tire_1k_0.geometry} material={materials.RB1c_Tire_1k} position={[0, -0.002, 0]} />
          </group>
          <group position={[-1.242, 0.326, 0.856]} rotation={[-Math.PI / 2, 0, 0]} scale={[1.01, 0.956, 1.01]}>
            <mesh geometry={nodes.Phoenix445_CaliperStock_RR_RB1c_Tire_1k_0.geometry} material={materials.RB1c_Tire_1k} position={[0, -0.002, 0]} />
          </group>
        </group>
      </group>
    </group>
  )
});


useGLTF.preload('/models/phonix/scene.gltf')
