/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 D:\buster\car\Mangos\public\data\Exports\gltf\Brick_Inset_Window_Curved_Small.gltf -o D:\buster\car\Mangos\scripts\src\components\city\BrickInsetWindowCurvedSmall.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Brick_Inset_Window_Curved_Small.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube205.geometry} material={materials.MI_RedBrick_Pale} />
      <mesh geometry={nodes.Cube205_1.geometry} material={materials.MI_Trim} />
      <mesh geometry={nodes.Cube205_2.geometry} material={materials.MI_Glass} />
      <mesh geometry={nodes.Cube205_3.geometry} material={materials.MI_InteriorWall} />
      <mesh geometry={nodes.Cube205_4.geometry} material={materials.MI_FakeInterior} />
    </group>
  )
}

useGLTF.preload('/Brick_Inset_Window_Curved_Small.gltf')
