/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 D:\buster\car\Mangos\public\data\Exports\gltf\Brick_RedWhite_DoubleWindow.gltf -o D:\buster\car\Mangos\scripts\src\components\city\BrickRedWhiteDoubleWindow.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Brick_RedWhite_DoubleWindow.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube238.geometry} material={materials.MI_InteriorWall} />
      <mesh geometry={nodes.Cube238_1.geometry} material={materials.MI_Trim} />
      <mesh geometry={nodes.Cube238_2.geometry} material={materials.MI_RedBrick_Pale} />
      <mesh geometry={nodes.Cube238_3.geometry} material={materials.MI_Trim_MetalConcrete} />
      <mesh geometry={nodes.Cube238_4.geometry} material={materials.MI_Glass} />
      <mesh geometry={nodes.Cube238_5.geometry} material={materials.MI_FakeInterior} />
    </group>
  )
}

useGLTF.preload('/Brick_RedWhite_DoubleWindow.gltf')
