/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 D:\buster\car\Mangos\public\data\Exports\gltf\Brick_BottomTrim.gltf -o D:\buster\car\Mangos\scripts\src\components\city\BrickBottomTrim.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Brick_BottomTrim.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube037.geometry} material={materials.MI_RedBrick} />
      <mesh geometry={nodes.Cube037_1.geometry} material={materials.MI_Trim} />
      <mesh geometry={nodes.Cube037_2.geometry} material={materials.MI_InteriorWall} />
    </group>
  )
}

useGLTF.preload('/Brick_BottomTrim.gltf')
