/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 D:\buster\car\Mangos\public\data\Exports\gltf\Brick_CornerColumn_Center_Half.gltf -o D:\buster\car\Mangos\scripts\src\components\city\BrickCornerColumnCenterHalf.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Brick_CornerColumn_Center_Half.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Brick_CornerColumn_Center_Half.geometry} material={materials.MI_RedBrick_Pale} rotation={[0, -Math.PI / 2, 0]} />
    </group>
  )
}

useGLTF.preload('/Brick_CornerColumn_Center_Half.gltf')
