/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 D:\buster\car\Mangos\public\data\Exports\gltf\Brick_TopTrim_90Angle_L.gltf -o D:\buster\car\Mangos\scripts\src\components\city\BrickTopTrim90AngleL.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Brick_TopTrim_90Angle_L.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube092.geometry} material={materials.MI_RedBrick_Pale} />
      <mesh geometry={nodes.Cube092_1.geometry} material={materials.MI_Trim} />
      <mesh geometry={nodes.Cube092_2.geometry} material={materials.MI_InteriorWall} />
    </group>
  )
}

useGLTF.preload('/Brick_TopTrim_90Angle_L.gltf')
