/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 D:\buster\car\Mangos\public\data\Exports\gltf\Brick_InteriorWall_4.gltf -o D:\buster\car\Mangos\scripts\src\components\city\BrickInteriorWall4.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Brick_InteriorWall_4.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Brick_InteriorWall_4.geometry} material={materials.MI_InteriorWall} />
    </group>
  )
}

useGLTF.preload('/Brick_InteriorWall_4.gltf')
