/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 D:\buster\car\Mangos\public\data\Exports\gltf\Building_Large_2.gltf -o D:\buster\car\Mangos\scripts\src\components\city\BuildingLarge2.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/Building_Large_2.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plane235.geometry} material={materials.MI_InteriorFloor} />
      <mesh geometry={nodes.Plane235_1.geometry} material={materials.MI_Trim_Dark} />
      <mesh geometry={nodes.Plane235_2.geometry} material={materials.MI_Trim_MetalConcrete} />
      <mesh geometry={nodes.Plane235_3.geometry} material={materials.MI_InteriorWall} />
      <mesh geometry={nodes.Plane235_4.geometry} material={materials.MI_Glass} />
      <mesh geometry={nodes.Plane235_5.geometry} material={materials.MI_FakeInterior_2} />
      <mesh geometry={nodes.Plane235_6.geometry} material={materials.MI_FakeInterior_3} />
      <mesh geometry={nodes.Plane235_7.geometry} material={materials.MI_RedBrick} />
      <mesh geometry={nodes.Plane235_8.geometry} material={materials.MI_FakeInterior_1} />
      <mesh geometry={nodes.Plane235_9.geometry} material={materials.MI_FakeInterior_4} />
      <mesh geometry={nodes.Plane235_10.geometry} material={materials.MI_Trim} />
      <mesh geometry={nodes.Plane235_11.geometry} material={materials.MI_Asphalt} />
    </group>
  )
}

useGLTF.preload('/Building_Large_2.gltf')
