/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 D:\buster\car\Mangos\public\data\Exports\gltf\Building_Medium_2_001.gltf -o D:\buster\car\Mangos\scripts\src\components\city\BuildingMedium2001.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Building_Medium_2_001.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plane002.geometry} material={materials.MI_InteriorFloor} />
      <mesh geometry={nodes.Plane002_1.geometry} material={materials.MI_Trim_Green} />
      <mesh geometry={nodes.Plane002_2.geometry} material={materials.MI_FakeInterior_1} />
      <mesh geometry={nodes.Plane002_3.geometry} material={materials.MI_FakeInterior_2} />
      <mesh geometry={nodes.Plane002_4.geometry} material={materials.MI_FakeInterior_3} />
      <mesh geometry={nodes.Plane002_5.geometry} material={materials.MI_FakeInterior_4} />
      <mesh geometry={nodes.Plane002_6.geometry} material={materials.MI_InteriorWall} />
      <mesh geometry={nodes.Plane002_7.geometry} material={materials.MI_Trim} />
      <mesh geometry={nodes.Plane002_8.geometry} material={materials.MI_Glass} />
      <mesh geometry={nodes.Plane002_9.geometry} material={materials.MI_Trim_Dark} />
      <mesh geometry={nodes.Plane002_10.geometry} material={materials.MI_RedBrick} />
      <mesh geometry={nodes.Plane002_11.geometry} material={materials.MI_Asphalt} />
    </group>
  )
}

useGLTF.preload('/Building_Medium_2_001.gltf')
