/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 D:\buster\car\Mangos\public\data\Exports\gltf\Building_Small_1.gltf -o D:\buster\car\Mangos\scripts\src\components\city\BuildingSmall1.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import gltfUrl from './Building_Small_1.gltf?url'

export default function Model(props) {
  const { nodes, materials } = useGLTF(gltfUrl)
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube5047.geometry} material={materials.MI_RedBrick_Pale} />
      <mesh geometry={nodes.Cube5047_1.geometry} material={materials.MI_Trim} />
      <mesh geometry={nodes.Cube5047_2.geometry} material={materials.MI_InteriorWall} />
      <mesh geometry={nodes.Cube5047_3.geometry} material={materials.MI_Trim_MetalConcrete} />
      <mesh geometry={nodes.Cube5047_4.geometry} material={materials.MI_Glass} />
      <mesh geometry={nodes.Cube5047_5.geometry} material={materials.MI_FakeInterior_2} />
      <mesh geometry={nodes.Cube5047_6.geometry} material={materials.MI_Trim_Dark} />
      <mesh geometry={nodes.Cube5047_7.geometry} material={materials.MI_FakeInterior_1} />
      <mesh geometry={nodes.Cube5047_8.geometry} material={materials.MI_Concrete} />
      <mesh geometry={nodes.Cube5047_9.geometry} material={materials.MI_FakeInterior_4} />
      <mesh geometry={nodes.Cube5047_10.geometry} material={materials.MI_FakeInterior_3} />
      <mesh geometry={nodes.Cube5047_11.geometry} material={materials.MI_Asphalt} />
      <mesh geometry={nodes.Cube5047_12.geometry} material={materials.MI_InteriorFloor} />
    </group>
  )
}

useGLTF.preload(gltfUrl)
