/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 D:\buster\car\Mangos\public\data\Exports\gltf\Cornice_Metal_L.gltf -o D:\buster\car\Mangos\scripts\src\components\city\CorniceMetalL.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Cornice_Metal_L.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cornice_Metal_L.geometry} material={materials.MI_Trim_MetalConcrete} />
    </group>
  )
}

useGLTF.preload('/Cornice_Metal_L.gltf')
