/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 D:\buster\car\Mangos\public\data\Exports\gltf\Cornice_Trim_90Angle_L.gltf -o D:\buster\car\Mangos\scripts\src\components\city\CorniceTrim90AngleL.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Cornice_Trim_90Angle_L.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cornice_Trim_90Angle_L.geometry} material={materials.MI_Trim} />
    </group>
  )
}

useGLTF.preload('/Cornice_Trim_90Angle_L.gltf')
