/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 D:\buster\car\Mangos\public\data\Exports\gltf\Decal_ArrowTurnRight.gltf -o D:\buster\car\Mangos\scripts\src\components\city\DecalArrowTurnRight.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Decal_ArrowTurnRight.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Decal_ArrowTurnRight.geometry} material={materials.MI_StreetDecals} />
    </group>
  )
}

useGLTF.preload('/Decal_ArrowTurnRight.gltf')
