/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 D:\buster\car\Mangos\public\data\Exports\gltf\Door_3.gltf -o D:\buster\car\Mangos\scripts\src\components\city\Door3.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Door_3.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube206.geometry} material={materials.MI_Trim_MetalConcrete} />
      <mesh geometry={nodes.Cube206_1.geometry} material={materials.MI_Glass} />
    </group>
  )
}

useGLTF.preload('/Door_3.gltf')
