/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 D:\buster\car\Mangos\public\data\Exports\gltf\DoorFrame_Metal_Single.gltf -o D:\buster\car\Mangos\scripts\src\components\city\DoorFrameMetalSingle.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/DoorFrame_Metal_Single.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube192.geometry} material={materials.MI_Trim_MetalConcrete} />
      <mesh geometry={nodes.Cube192_1.geometry} material={materials.MI_Glass} />
    </group>
  )
}

useGLTF.preload('/DoorFrame_Metal_Single.gltf')
