/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 D:\buster\car\Mangos\public\data\Exports\gltf\DoorFrame_Wooden.gltf -o D:\buster\car\Mangos\scripts\src\components\city\DoorFrameWooden.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/DoorFrame_Wooden.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube203.geometry} material={materials.MI_Trim} />
      <mesh geometry={nodes.Cube203_1.geometry} material={materials.MI_Glass} />
    </group>
  )
}

useGLTF.preload('/DoorFrame_Wooden.gltf')
