/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 D:\buster\car\Mangos\public\data\Exports\gltf\Metal_Column_Bottom.gltf -o D:\buster\car\Mangos\scripts\src\components\city\MetalColumnBottom.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Metal_Column_Bottom.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Metal_Column_Bottom.geometry} material={materials.MI_Trim_MetalConcrete} />
    </group>
  )
}

useGLTF.preload('/Metal_Column_Bottom.gltf')
