/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 D:\buster\car\Mangos\public\data\Exports\gltf\Metal_FullWindow.gltf -o D:\buster\car\Mangos\scripts\src\components\city\MetalFullWindow.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Metal_FullWindow.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube168.geometry} material={materials.MI_Trim_MetalConcrete} />
      <mesh geometry={nodes.Cube168_1.geometry} material={materials.MI_Glass} />
      <mesh geometry={nodes.Cube168_2.geometry} material={materials.MI_FakeInterior} />
    </group>
  )
}

useGLTF.preload('/Metal_FullWindow.gltf')
