/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 D:\buster\car\Mangos\public\data\Exports\gltf\Prop_ACUnit.gltf -o D:\buster\car\Mangos\scripts\src\components\city\PropACUnit.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Prop_ACUnit.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Prop_ACUnit.geometry} material={materials.MI_Ornaments} />
    </group>
  )
}

useGLTF.preload('/Prop_ACUnit.gltf')
