/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 D:\buster\car\Mangos\public\data\Exports\gltf\Roof_SlateCornice_InnerCorner.gltf -o D:\buster\car\Mangos\scripts\src\components\city\RoofSlateCorniceInnerCorner.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Roof_SlateCornice_InnerCorner.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plane057.geometry} material={materials.MI_Roof_Slate} />
      <mesh geometry={nodes.Plane057_1.geometry} material={materials.MI_Trim_MetalConcrete} />
      <mesh geometry={nodes.Plane057_2.geometry} material={materials.MI_Trim} />
    </group>
  )
}

useGLTF.preload('/Roof_SlateCornice_InnerCorner.gltf')
