/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 D:\buster\car\Mangos\public\data\Exports\gltf\Roof_2x2_90Angle_R.gltf -o D:\buster\car\Mangos\scripts\src\components\city\Roof2x290AngleR.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Roof_2x2_90Angle_R.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Roof_2x2_90Angle_R.geometry} material={materials.MI_Asphalt} />
    </group>
  )
}

useGLTF.preload('/Roof_2x2_90Angle_R.gltf')
