/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 D:\buster\car\Mangos\public\data\Exports\gltf\Roof_SlateCornice_Center.gltf -o D:\buster\car\Mangos\scripts\src\components\city\RoofSlateCorniceCenter.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Roof_SlateCornice_Center.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plane.geometry} material={materials.MI_Roof_Slate} />
      <mesh geometry={nodes.Plane_1.geometry} material={materials.MI_Trim_MetalConcrete} />
      <mesh geometry={nodes.Plane_2.geometry} material={materials.MI_Trim} />
    </group>
  )
}

useGLTF.preload('/Roof_SlateCornice_Center.gltf')
