/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 D:\buster\car\Mangos\public\data\Exports\gltf\Stairs_Rails_Metal_Straight_1.gltf -o D:\buster\car\Mangos\scripts\src\components\city\StairsRailsMetalStraight1.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Stairs_Rails_Metal_Straight_1.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Stairs_Rails_Metal_Straight_1.geometry} material={materials.MI_Trim_MetalConcrete} />
    </group>
  )
}

useGLTF.preload('/Stairs_Rails_Metal_Straight_1.gltf')
