/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 D:\buster\car\Mangos\public\data\Exports\gltf\Street_Curve_2Lane_Curb.gltf -o D:\buster\car\Mangos\scripts\src\components\city\StreetCurve2LaneCurb.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Street_Curve_2Lane_Curb.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Street_Curve_2Lane_Curb.geometry} material={materials.MI_Trim_MetalConcrete} />
    </group>
  )
}

useGLTF.preload('/Street_Curve_2Lane_Curb.gltf')
