/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 D:\buster\car\Mangos\public\data\Exports\gltf\Street_2Lane_noSidewalk.gltf -o D:\buster\car\Mangos\scripts\src\components\city\Street2LaneNoSidewalk.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Street_2Lane_noSidewalk.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plane228.geometry} material={materials.MI_Asphalt} />
      <mesh geometry={nodes.Plane228_1.geometry} material={materials.MI_StreetDecals} />
    </group>
  )
}

useGLTF.preload('/Street_2Lane_noSidewalk.gltf')
