/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 D:\buster\car\Mangos\public\data\Exports\gltf\Street_4Lane_noSidewalk.gltf -o D:\buster\car\Mangos\scripts\src\components\city\Street4LaneNoSidewalk.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Street_4Lane_noSidewalk.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plane232.geometry} material={materials.MI_Asphalt} />
      <mesh geometry={nodes.Plane232_1.geometry} material={materials.MI_StreetDecals} />
    </group>
  )
}

useGLTF.preload('/Street_4Lane_noSidewalk.gltf')
