/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 D:\buster\car\Mangos\public\data\Exports\gltf\Trim_Plain_3.gltf -o D:\buster\car\Mangos\scripts\src\components\city\TrimPlain3.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Trim_Plain_3.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube039.geometry} material={materials.MI_Trim} />
      <mesh geometry={nodes.Cube039_1.geometry} material={materials.MI_InteriorWall} />
    </group>
  )
}

useGLTF.preload('/Trim_Plain_3.gltf')
