/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 D:\buster\car\Mangos\public\data\Exports\gltf\Trim_Window.gltf -o D:\buster\car\Mangos\scripts\src\components\city\TrimWindow.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Trim_Window.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube862.geometry} material={materials.MI_Trim} />
      <mesh geometry={nodes.Cube862_1.geometry} material={materials.MI_Glass} />
      <mesh geometry={nodes.Cube862_2.geometry} material={materials.MI_Trim_Dark} />
      <mesh geometry={nodes.Cube862_3.geometry} material={materials.MI_FakeInterior} />
      <mesh geometry={nodes.Cube862_4.geometry} material={materials.MI_InteriorWall} />
    </group>
  )
}

useGLTF.preload('/Trim_Window.gltf')
