/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 D:\buster\car\Mangos\public\data\Exports\gltf\Brick_Window_CurvedDouble.gltf -o D:\buster\car\Mangos\scripts\src\components\city\BrickWindowCurvedDouble.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Brick_Window_CurvedDouble.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube240.geometry} material={materials.MI_RedBrick_Pale} />
      <mesh geometry={nodes.Cube240_1.geometry} material={materials.MI_InteriorWall} />
      <mesh geometry={nodes.Cube240_2.geometry} material={materials.MI_Trim_MetalConcrete} />
      <mesh geometry={nodes.Cube240_3.geometry} material={materials.MI_Glass} />
      <mesh geometry={nodes.Cube240_4.geometry} material={materials.MI_FakeInterior} />
    </group>
  )
}

useGLTF.preload('/Brick_Window_CurvedDouble.gltf')
