/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 D:\buster\car\Mangos\public\data\Exports\gltf\Brick_HalfColumn_Top.gltf -o D:\buster\car\Mangos\scripts\src\components\city\BrickHalfColumnTop.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Brick_HalfColumn_Top.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube099.geometry} material={materials.MI_RedBrick} />
      <mesh geometry={nodes.Cube099_1.geometry} material={materials.MI_Trim} />
    </group>
  )
}

useGLTF.preload('/Brick_HalfColumn_Top.gltf')
