/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 D:\buster\car\Mangos\public\data\Exports\gltf\Brick_Column_RedBricks.gltf -o D:\buster\car\Mangos\scripts\src\components\city\BrickColumnRedBricks.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Brick_Column_RedBricks.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Brick_Column_RedBricks.geometry} material={materials.MI_RedBrick} />
    </group>
  )
}

useGLTF.preload('/Brick_Column_RedBricks.gltf')
