/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 D:\buster\car\Mangos\public\data\Exports\gltf\Brick_Window_Square_Single.gltf -o D:\buster\car\Mangos\scripts\src\components\city\BrickWindowSquareSingle.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Brick_Window_Square_Single.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube185.geometry} material={materials.MI_RedBrick_Pale} />
      <mesh geometry={nodes.Cube185_1.geometry} material={materials.MI_Trim} />
      <mesh geometry={nodes.Cube185_2.geometry} material={materials.MI_Glass} />
      <mesh geometry={nodes.Cube185_3.geometry} material={materials.MI_FakeInterior} />
      <mesh geometry={nodes.Cube185_4.geometry} material={materials.MI_InteriorWall} />
    </group>
  )
}

useGLTF.preload('/Brick_Window_Square_Single.gltf')
