/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 D:\buster\car\Mangos\public\data\Exports\gltf\Brick_CornerColumn_Cap.gltf -o D:\buster\car\Mangos\scripts\src\components\city\BrickCornerColumnCap.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Brick_CornerColumn_Cap.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube260.geometry} material={materials.MI_RedBrick_Pale} />
      <mesh geometry={nodes.Cube260_1.geometry} material={materials.MI_Trim} />
    </group>
  )
}

useGLTF.preload('/Brick_CornerColumn_Cap.gltf')
