/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 D:\buster\car\Mangos\public\data\Exports\gltf\Decal_Crosswalk_Wide.gltf -o D:\buster\car\Mangos\scripts\src\components\city\DecalCrosswalkWide.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Decal_Crosswalk_Wide.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Decal_Crosswalk_Wide.geometry} material={materials.MI_StreetDecals} scale={[1.485, 1, 1]} />
    </group>
  )
}

useGLTF.preload('/Decal_Crosswalk_Wide.gltf')
