/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 D:\buster\car\Mangos\public\data\Exports\gltf\DoorFrame_Trim.gltf -o D:\buster\car\Mangos\scripts\src\components\city\DoorFrameTrim.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/DoorFrame_Trim.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube096.geometry} material={materials.MI_Trim_Green} />
      <mesh geometry={nodes.Cube096_1.geometry} material={materials.MI_Glass} />
      <mesh geometry={nodes.Cube096_2.geometry} material={materials.MI_Trim} />
      <mesh geometry={nodes.Cube096_3.geometry} material={materials.MI_InteriorWall} />
    </group>
  )
}

useGLTF.preload('/DoorFrame_Trim.gltf')
