/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 D:\buster\car\Mangos\public\data\Exports\gltf\Floor_2x2.gltf -o D:\buster\car\Mangos\scripts\src\components\city\Floor2x2.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Floor_2x2.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plane013.geometry} material={materials.MI_InteriorFloor} />
      <mesh geometry={nodes.Plane013_1.geometry} material={materials.MI_InteriorRoof} />
    </group>
  )
}

useGLTF.preload('/Floor_2x2.gltf')
