/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 D:\buster\car\Mangos\public\data\Exports\gltf\Metal_FirstFloor_Wall.gltf -o D:\buster\car\Mangos\scripts\src\components\city\MetalFirstFloorWall.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Metal_FirstFloor_Wall.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube052.geometry} material={materials.MI_Trim_Dark} />
      <mesh geometry={nodes.Cube052_1.geometry} material={materials.MI_Trim_MetalConcrete} />
      <mesh geometry={nodes.Cube052_2.geometry} material={materials.MI_InteriorWall} />
    </group>
  )
}

useGLTF.preload('/Metal_FirstFloor_Wall.gltf')
