/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 D:\buster\car\Mangos\public\data\Exports\gltf\Metal_FirstFloor_Window.gltf -o D:\buster\car\Mangos\scripts\src\components\city\MetalFirstFloorWindow.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Metal_FirstFloor_Window.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube007.geometry} material={materials.MI_Trim_Dark} />
      <mesh geometry={nodes.Cube007_1.geometry} material={materials.MI_Trim_MetalConcrete} />
      <mesh geometry={nodes.Cube007_2.geometry} material={materials.MI_Glass} />
      <mesh geometry={nodes.Cube007_3.geometry} material={materials.MI_FakeInterior} />
      <mesh geometry={nodes.Cube007_4.geometry} material={materials.MI_InteriorWall} />
    </group>
  )
}

useGLTF.preload('/Metal_FirstFloor_Window.gltf')
