/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 D:\buster\car\Mangos\public\data\Exports\gltf\Prop_Planter_Single.gltf -o D:\buster\car\Mangos\scripts\src\components\city\PropPlanterSingle.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Prop_Planter_Single.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube016.geometry} material={materials.MI_Trim_MetalConcrete} />
      <mesh geometry={nodes.Cube016_1.geometry} material={materials.MI_Dirt} />
    </group>
  )
}

useGLTF.preload('/Prop_Planter_Single.gltf')
