/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 D:\buster\car\Mangos\public\data\Exports\gltf\Roof_Slate_InnerCorner.gltf -o D:\buster\car\Mangos\scripts\src\components\city\RoofSlateInnerCorner.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Roof_Slate_InnerCorner.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plane005.geometry} material={materials.MI_Roof_Slate} />
      <mesh geometry={nodes.Plane005_1.geometry} material={materials.MI_Trim_MetalConcrete} />
    </group>
  )
}

useGLTF.preload('/Roof_Slate_InnerCorner.gltf')
