/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 D:\buster\car\Mangos\public\data\Exports\gltf\Roof_4x4.gltf -o D:\buster\car\Mangos\scripts\src\components\city\Roof4x4.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Roof_4x4.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Roof_4x4.geometry} material={materials.MI_Asphalt} />
    </group>
  )
}

useGLTF.preload('/Roof_4x4.gltf')
