/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 D:\buster\car\Mangos\public\data\Exports\gltf\Roof_SlateCornice_Window_1.gltf -o D:\buster\car\Mangos\scripts\src\components\city\RoofSlateCorniceWindow1.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Roof_SlateCornice_Window_1.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plane017.geometry} material={materials.MI_Roof_Slate} />
      <mesh geometry={nodes.Plane017_1.geometry} material={materials.MI_Trim} />
      <mesh geometry={nodes.Plane017_2.geometry} material={materials.MI_Glass} />
      <mesh geometry={nodes.Plane017_3.geometry} material={materials.MI_FakeInterior} />
      <mesh geometry={nodes.Plane017_4.geometry} material={materials.MI_Trim_MetalConcrete} />
    </group>
  )
}

useGLTF.preload('/Roof_SlateCornice_Window_1.gltf')
