/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 D:\buster\car\Mangos\public\data\Exports\gltf\Sidewalk_NoCurb_3m.gltf -o D:\buster\car\Mangos\scripts\src\components\city\SidewalkNoCurb3m.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Sidewalk_NoCurb_3m.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Sidewalk_NoCurb_3m.geometry} material={materials.MI_Trim_MetalConcrete} />
    </group>
  )
}

useGLTF.preload('/Sidewalk_NoCurb_3m.gltf')
