/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 D:\buster\car\Mangos\public\data\Exports\gltf\Sidewalk_Planter.gltf -o D:\buster\car\Mangos\scripts\src\components\city\SidewalkPlanter.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Sidewalk_Planter.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube11762.geometry} material={materials.MI_Trim_MetalConcrete} />
      <mesh geometry={nodes.Cube11762_1.geometry} material={materials.MI_Dirt} />
    </group>
  )
}

useGLTF.preload('/Sidewalk_Planter.gltf')
