/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 D:\buster\car\Mangos\public\data\Exports\gltf\Stairs_Entrance_Concrete.gltf -o D:\buster\car\Mangos\scripts\src\components\city\StairsEntranceConcrete.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Stairs_Entrance_Concrete.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube066.geometry} material={materials.MI_Trim_MetalConcrete} />
      <mesh geometry={nodes.Cube066_1.geometry} material={materials.MI_Concrete} />
    </group>
  )
}

useGLTF.preload('/Stairs_Entrance_Concrete.gltf')
