/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 D:\buster\car\Mangos\public\data\Exports\gltf\Street_Asphalt_6x6.gltf -o D:\buster\car\Mangos\scripts\src\components\city\StreetAsphalt6x6.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Street_Asphalt_6x6.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Street_Asphalt_6x6.geometry} material={materials.MI_Asphalt} />
    </group>
  )
}

useGLTF.preload('/Street_Asphalt_6x6.gltf')
