/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 D:\buster\car\Mangos\public\data\Exports\gltf\Trim_Wall_Guard.gltf -o D:\buster\car\Mangos\scripts\src\components\city\TrimWallGuard.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Trim_Wall_Guard.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Trim_Wall_Guard.geometry} material={materials.MI_Trim_Green} />
    </group>
  )
}

useGLTF.preload('/Trim_Wall_Guard.gltf')
