/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 D:\buster\car\Mangos\public\data\Exports\gltf\Trim_Column_Center.gltf -o D:\buster\car\Mangos\scripts\src\components\city\TrimColumnCenter.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Trim_Column_Center.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Trim_Column_Center.geometry} material={materials.MI_Trim} />
    </group>
  )
}

useGLTF.preload('/Trim_Column_Center.gltf')
