/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 D:\buster\car\Mangos\public\data\Exports\gltf\Trim_FirstFloor_Window_001.gltf -o D:\buster\car\Mangos\scripts\src\components\city\TrimFirstFloorWindow001.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Trim_FirstFloor_Window_001.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube001.geometry} material={materials.MI_Trim_Green} />
      <mesh geometry={nodes.Cube001_1.geometry} material={materials.MI_FakeInterior} />
      <mesh geometry={nodes.Cube001_2.geometry} material={materials.MI_InteriorWall} />
      <mesh geometry={nodes.Cube001_3.geometry} material={materials.MI_Glass} />
    </group>
  )
}

useGLTF.preload('/Trim_FirstFloor_Window_001.gltf')
